ProjectManager/PMApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),

    path("switch_project/", views.switch_project, name="switch_project"),
    path("switch_project/<int:project_id>", views.switch_project, name="switch_project"),
    path("create_project/", views.create_project, name="create_project"),
    path("view_project/", views.view_project, name="view_project"),
    path("update_project/", views.update_project, name="update_project"),
    path("archive_project/", views.archive_project, name="archive_project"),
    path("delete_project/", views.delete_project, name="delete_project"),

    path("view_members/", views.view_members, name="view_members"),
    path("remove_member/<int:member_id>", views.remove_member, name="remove_member"),
    path("add_member", views.add_member, name="add_member"),

    path("create_task/", views.create_task, name="create_task"),
    path("update_task/<int:task_id>", views.update_task, name="update_task"),
    path("delete_task/", views.delete_task, name="delete_task"),

    path("create_expense/", views.create_expense, name="create_expense"),
    path("update_expense/<int:expense_id>", views.update_expense, name="update_expense"),
    path("delete_expense/", views.delete_expense, name="delete_expense"),
]

ProjectManager/ProjectManager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("PMApp.urls"))
]

ProjectManager/PMApp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import date


class Project(models.Model):

    class Status(models.IntegerChoices):
        ONGOING = 0, _("Ongoing")
        FINISHED = 1, _("Finished")
        ARCHIVED = 2, _("Archived")

    project_id = models.SmallAutoField(primary_key=True)
    project_name = models.CharField(max_length=255)
    project_desc = models.TextField()
    project_start = models.DateField(default=date.today)
    project_end = models.DateField(default=None, blank=True, null=True)
    project_status = models.IntegerField(choices=Status, default=Status.ONGOING)

    def __str__(self):
        return "{}: {} ({})".format(self.project_id, self.project_name, self.project_status)


class User(models.Model):

    class sType(models.TextChoices):
        EXECUTIVE = "X", _("Executive")
        MANAGER = "M", _("Manager")
        EMPLOYEE = "Em", _("Employee")

    user_id = models.SmallAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.BinaryField()
    # TODO: profile pics
    staff_type = models.CharField(max_length=2, choices=sType, default=sType.EMPLOYEE)

    def __str__(self):
        return "{}: {} ({})".format(self.user_id, self.name, self.staff_type)


class Member(models.Model):

    member_id = models.SmallAutoField(primary_key=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "{} is a member of {}".format(self.user.name, self.project.project_name)


class Task(models.Model):

    class Status(models.IntegerChoices):
        INPROGRESS = 0, _("In Progress")
        FORREVIEW = 1, _("For Review")
        COMPLETED = 2, _("Completed")
    
    class Priority(models.TextChoices):
        HIGH = "H", _("High")
        MEDIUM = "M", _("Medium")
        LOW = "L", _("Low")

    task_id = models.SmallAutoField(primary_key=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=255)
    task_notes = models.TextField(blank=True, null=True)
    task_deadline = models.DateField(default=date.today, blank=True, null=True)
    task_status = models.IntegerField(choices=Status, default=Status.INPROGRESS)
    task_priority = models.CharField(max_length=1, choices=Priority)

    def __str__(self):
        return "{}: {} ({} - {})".format(
            self.task_id,
            self.task_name,
            self.task_status,
            self.task_priority
        )


class TaskAssignment(models.Model):

    assignment_id = models.SmallAutoField(primary_key=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)

    def __str__(self):
        return "{} is tasked to {}".format(self.member.user.name, self.task.task_name)


class Expense(models.Model):

    expense_id = models.SmallAutoField(primary_key=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    expense_date = models.DateField(default=date.today)
    expense_desc = models.TextField()
    expense_amt = models.DecimalField(max_digits=11, decimal_places=2)  # TODO: Change in data dictionary

    def __str__(self):
        return "{}: PHP {} to {}".format(
            self.expense_id,
            self.expense_amt,
            self.project.project_name
        )


class Notification(models.Model):

    class Status(models.IntegerChoices):
        UNREAD = 0, _("Unread")
        READ = 1, _("Read")

    notif_id = models.SmallAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notif_datetime = models.DateTimeField()
    notif_text = models.CharField(max_length=255)
    notif_status = models.IntegerField(choices=Status, default=Status.UNREAD)

ProjectManager/PMApp/views.py
from django.shortcuts import render, redirect, Http404
from django.http import HttpResponse
from django.db.models import Case, Value, When

from .models import Project, User, Member, Task, TaskAssignment, Expense

import bcrypt
import datetime 

def login(request):
    if request.method == "POST":
        # Get form fields
        username = request.POST.get("username")
        password = request.POST.get("password")

        # Validate username
        try:
            user_obj = User.objects.get(username=username)
        except:
            return render(request, "login.html", {"error": True})
        
        # Validate password
        bytes = password.encode('utf-8')
        password_matches = bcrypt.checkpw(bytes, user_obj.password) 
        if not password_matches:
            return render(request, "login.html", {"error": True})
        
        # Login successful
        response = redirect("dashboard")
        response.set_cookie("user_id", user_obj.user_id)
        return response

    else:
        return render(request, "login.html")


def register(request):
    if request.method == "POST":
        # Get form fields
        name = request.POST.get("name")
        username = request.POST.get("username")
        password = request.POST.get("password")
        retype_pass = request.POST.get("retype_pass")

        # Validate username
        if len(User.objects.filter(username=username)) != 0:
            return render(request, "register.html", {"username_error": True})
        
        # Validate password
        if password != retype_pass:
            return render(request, "register.html", {"password_error": True})
        
        # Hash password
        bytes = password.encode("utf-8")
        salt = bcrypt.gensalt()
        hash = bcrypt.hashpw(bytes, salt)

        user_obj = User.objects.create(
            name=name,
            username=username,
            password=hash,
            staff_type="Em"
        )
        
        # Login successful
        response = redirect("dashboard")
        response.set_cookie("user_id", user_obj.user_id)
        return response

    else:
        return render(request, "register.html")


def logout(request):
    response = redirect("login")
    response.delete_cookie("user_id")
    if request.session["current_project_id"]:
        del request.session["current_project_id"]
    request.session.modified = True
    return response


def dashboard(request):

    # Validate and retrieve current logged in user id
    user_id = request.COOKIES.get("user_id")

    if user_id is None:
        return redirect("login")
    
    # Retrieve user obj 
    user_obj = User.objects.get(user_id=user_id)

    # If manager/employee, get all projects the user is part of
    # If executive, get all projects
    if user_obj.staff_type != "X":
        project_objs = Project.objects.filter(member__user=user_obj)
    else:
        project_objs = Project.objects.all()

    # Get selected project obj
    try:
        project_id = request.session["current_project_id"]
        project_obj = Project.objects.get(project_id=project_id)
    except:
        # Default to the first project, when not specified
        if len(project_objs) > 0:
            project_obj = project_objs[0]
            project_id = project_obj.project_id
            request.session["current_project_id"] = project_id

        # If no project assigned, render empty dashboard
        else:
            request.session["current_project_id"] = None
            return render(
                request,
                "dashboard.html",
                {"user": user_obj,
                 "project": None,
                 "tasks_and_members": None,
                 "expenses": None,
                 "proj_members": None})
    
    priority_weights = Case(
            When(task_priority = Task.Priority.HIGH, then=Value(1)),
            When(task_priority = Task.Priority.MEDIUM, then=Value(2)),
            When(task_priority = Task.Priority.LOW, then=Value(3)),
            default = Value(3),)
    
    # Get tasks
    # If member is an employee, only show tasks for him/her
    if user_obj.staff_type == "Em":
        member_obj = Member.objects.get(project=project_obj, user=user_obj)
        task_objs = Task.objects.filter(project=project_obj, taskassignment__member=member_obj)
        task_objs = task_objs.order_by("task_status", priority_weights)
    else:
        task_objs = Task.objects.filter(project_id=project_id).order_by("task_status", priority_weights)

    # Get expenses
    # If member is an employee, only show tasks for him/her
    if user_obj.staff_type == "Em":
        expense_objs = Expense.objects.filter(project_id=project_id, member=member_obj)
    else:
        expense_objs = Expense.objects.filter(project_id=project_id)

    # Get members of the project for creating tasks
    proj_members_objs = Member.objects.filter(project=project_obj)

    # Get members of each task for displaying
    tasks_and_members = {}
    for task_obj in task_objs:
        member_objs = Member.objects.filter(taskassignment__task=task_obj)
        tasks_and_members[task_obj] = member_objs
    
    return render(request,
                  "dashboard.html",
                  {"user": user_obj,
                   "project": project_obj,
                   "tasks_and_members": tasks_and_members,
                   "expenses": expense_objs,
                   "proj_members": proj_members_objs})


def switch_project(request, project_id):

    # Validate and retrieve current logged in user id
    user_id = request.COOKIES.get("user_id")

    if user_id is None:
        return redirect("login")

    request.session["current_project_id"] = int(project_id)

    previous_url = request.META.get("HTTP_REFERER")
    previous_view = previous_url.rstrip('/').split('/')[-1]

    # If user was in update_project, redirect to view_project to prevent unwanted changes
    if previous_view == "update_project":
        previous_url = "view_project"

    return redirect(previous_url)


def create_project(request):

    # Validate and retrieve current logged in user id
    user_id = request.COOKIES.get("user_id")

    if user_id is None:
        return redirect("login")

    # Create project when user clicks submit
    if (request.method == "POST"):
            
        # Get submitted form values
        project_name = request.POST.get("project_name")
        project_desc = request.POST.get("project_desc")
        project_start = request.POST.get("project_start")
        project_end = request.POST.get("project_end")
        project_status = request.POST.get("project_status")
        members = [int(id) for id in request.POST.getlist('members')]

        # Set project end date to None if none specified
        if project_end == "":
            project_end = None

        # Create and save the new project
        new_project = Project.objects.create(
            project_name=project_name,
            project_desc=project_desc,
            project_start=project_start,
            project_end=project_end,
            project_status=project_status
        )

        # Automatically add the project manager as a member
        user_obj = User.objects.get(user_id=user_id)
        Member.objects.create(
            project = new_project,
            user = user_obj
        )

        # Add selected members as a member to the new project
        for member in members:
            new_user = User.objects.get(user_id = member)
            Member.objects.create(
                project = new_project,
                user = new_user
            )

        request.session["current_project_id"] = new_project.project_id
        return redirect("view_project")

    # Otherwise, display the form
    else:

        users = User.objects.exclude(staff_type="X").exclude(user_id=user_id)
        return render(request,
                      "create_project.html", {"users": users})


def view_project(request):

    # Retrieve current logged in user id
    user_id = request.COOKIES.get("user_id")

    if user_id is None:
        return redirect("login")

    project_id = request.session["current_project_id"]

    try:
        project_obj = Project.objects.get(project_id=project_id)
    except:
        raise Http404("Project does not exist")

    task_objs = Task.objects.filter(project__project_id = project_obj.project_id)

    completed_tasks = Task.objects.filter(project__project_id = project_obj.project_id, task_status = 2).count()
    review_tasks = Task.objects.filter(project__project_id = project_obj.project_id, task_status = 1).count()  
    progress_tasks = Task.objects.filter(project__project_id = project_obj.project_id, task_status = 0).count()

    if(completed_tasks != 0 and task_objs.count != 0):
        completed_tasks = (completed_tasks/task_objs.count()) * 100
    
    if(review_tasks != 0 and task_objs.count != 0):
        review_tasks = (review_tasks/task_objs.count()) * 100

    if(progress_tasks != 0 and task_objs.count != 0):
        progress_tasks = (progress_tasks / task_objs.count()) * 100

    start_to_now = (datetime.datetime.now().date() - project_obj.project_start).days

    if project_obj.project_end:
        end_to_now = (project_obj.project_end - datetime.datetime.now().date()).days
        start_to_end = (project_obj.project_end - project_obj.project_start).days
    else:
        end_to_now = 0
        start_to_end = 0
    
    if end_to_now < 0:
        start_to_now_percentage = 100
        end_to_now_percentage = 0
        start_to_now = start_to_end
    else:
        try:
            start_to_now_percentage = (start_to_now / start_to_end) * 100
        except:
            start_to_now_percentage = 0

        try:
            end_to_now_percentage = (end_to_now / start_to_end) * 100
        except:
            end_to_now_percentage = 0
        
    
    total_expenses = 0
    expense_objs = Expense.objects.filter(project_id=project_id)

ProjectManager/PMApp/templates/add_member.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'dashboard' %}">Dashboard</a></li>
      <li class="navbar-item"><a class="me-2" style="color: F8F9FA; text-decoration: none;" href="{% url 'view_members' %}">Members</a></li>
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'view_project' %}">Overview</a></li>
      <li><a class="mr-2" style="color: ADB5BD; text-decoration: none;" href="{% url "logout" %}">Logout</a></li>
{% endblock %}


{% block content %}
<div style="color: WHITE;">
  <form action="{% url "add_member" %}" method="POST"> {% csrf_token %}
    <div class="row ms-3">
      <div class="col">
        <h1> Team Members </h1>
      </div>
      <div class="col">
      </div>
    </div> 

    <div class="mb-3" style="height: 1px; background-color: #EAEFF5;"></div>

    <script>
      window.onscroll = function (){
        let vert_line = document.getElementById("vertical_line");  

        if(window.scrollY > 0){
          let scrolled = 130 - window.scrollY;
          vert_line.style.top = scrolled.toString() + 'px';
        }
        else{
          vert_line.style.top = "118px"
        }
      }
    </script>

    <div class="row mt-4 ms-3">
      <div class="col-5 scrollable">
        <table class="table table-striped rounded-3 overflow-hidden" style="width: 75%;">
          <thead class="table table-secondary table-striped">
            <tr>
              <th colspan="3" style="text-align: center"> Current Members </th>
            </tr>
            <tr>
              <th scope="col" style="width: 50%">Name</th>
              <th scope="col" style="width: 50%">Role</th>
            </tr>
          </thead>
          <tbody>
            {% for member in members %}
                <tr>
                  <td scope="col"> {{ member.user.name }} </td>
                  <td scope="col"> {{ member.user.get_staff_type_display }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="col scrollable">
        <div class="col"> 
          <h3> Available Users </h3>
        </div>

        {% for user in users %}
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="{{ user.user_id }}" name="member" id="user{{user.user_id}}">
            <label class="form-check-label" for="user{{user.user_id}}">
              <b>{{ user.name }}</b> ({{ user.get_staff_type_display}})
            </label>
          </div>
        {% endfor %}      

        <div class="col">
          <div class="mt-4">
            <input class="btn me-3 btn-outline-secondary" style="color: WHITE;" type="submit">
            <a href="{% url 'view_members' %}">
              <button class="btn btn-outline-light me-3" type="button">Cancel</button>
            </a>
          </div>
        </div>

      </div>

    </div>
  </form>
</div>
{% endblock %}

ProjectManager/PMApp/templates/base.html
{% load static %}
<html>
<head>
    <title>Project Manager</title>

    <link rel="stylesheet" href="{% static 'custom.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">

  <style>
    h1 {
      font-size: 36px;
    }

    h2 {
      font-size: 32px;
    }

    h3 {
      font-size: 24px;
    }
  </style>

    <script src="{% static 'scripts.js'%}"></script>
    <script src="{% static '/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</head>

<body style="background-color: 272727;">
  <div style="background-color: 343A40;">
    <nav class="navbar navbar-expand-lg" style="height: 60px">
      <ul class="navbar-nav mt-3">

        <li class="navbar-item me-2">
            <img style="width: 142px; height: auto; position: relative; bottom:5px;" src="{%static 'images/Atman Logo.png'%}">
            </img>
        </li>

        <li class="navbar-item me-2" style="color: ADB5BD;">
          {{ user.name }} ({{ user.staff_type }})
        </li>
        
        {% block navbar %}
        {% endblock %}
      </ul>
        {% block project_selector %}
          <!-- Project selector -->
          <select class="form-select form-select-sm me-2 rounded-3 overflow-hidden" style="position: absolute; left: 60%; width: 35%;" name="project_selector" id="project_selector">
          {% for project in projects %}
              <option value="{{ project.project_id }}" {% if project.project_id == request.session.current_project_id %}selected{% endif %}>{{ project.project_name }}{% if project.project_status == 1 or project.project_status == 2 %} ({{ project.get_project_status_display }}){% endif %}</option>
          {% endfor %}
          </select>
          {% if user.staff_type == "M" %}
          <a href="{% url 'create_project' %}" style="text-decoration: none; margin-bottom: 30px;">
            <button class="rounded-5" style="width: 32px; height: 32px; position: absolute; left: 96%; text-align: center;">
              +
            </button>
          </a>
          {% endif %}
        {% endblock %}
    </nav>
  </div>
    <div class="body">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

ProjectManager/PMApp/templates/create_project.html
{% extends 'base.html' %}

{% block navbar %}
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'dashboard' %}">Dashboard</a></li>
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'view_members' %}">Members</a></li>
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'view_project' %}">Overview</a></li>
      <li><a class="mr-2" style="color: ADB5BD; text-decoration: none;" href="{% url "logout" %}">Logout</a></li>
{% endblock %}

{% block content %}

    <form action="{% url 'create_project' %}" method="POST">{% csrf_token %}
      <div class="row mt-4 ms-3">
        <div class="col-5">
          <label for="project_name">Project Name:</label>
          <input class="form-control" type="text" name="project_name" id="project_name" required><br><br>

          <label for="project_desc">Project Description:</label>
          <textarea class="form-control" name="project_desc" id="project_desc" cols="70" rows="10" required></textarea><br><br>

          <label for="project_start">Project Start:</label>
          <input class="rounded-2" type="date" name="project_start" id="project_start" required><br><br>

          <label for="project_end">Project End:</label>
          <input class="rounded-2" type="date" name="project_end" id="project_end"><br><br>

          <label for="project_status">Project Status:</label>
          <select class="rounded-3" name="project_status" id="project_status">
              <option value="0">Ongoing</option>
              <option value="1">Finished</option>
          </select>

          <br><br>
          
          <input class="btn btn-outline-secondary rounded-3" style="color: WHITE;" type="submit">
          <a href="{% url 'dashboard' %}">
            <button class="btn btn-outline-light rounded-3" style="color: WHITE;" type="button">Cancel</button>
          </a>
        </div>

        <div class="col mt-3 ms-5">
          <label>Members:</label>

          {% for user in users %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="{{ user.user_id }}" name="members" id="member{{ user.user_id}}">
              <label class="form-check-label" for="member{{ user.user_id }}">
                <b>{{ user.name }}</b> ({{ user.get_staff_type_display}})
              </label>
            </div>
          {% endfor %}

        </div>

    </form>
    <script>
        // Set default project start to today's date
        document.getElementById("project_start").valueAsDate = new Date();

        // Prevent startdate > enddate
        document.querySelector('form').addEventListener('submit', function(event) {
          event.preventDefault(); // Prevent form submission

          var startDate = new Date(document.getElementById('project_start').value);
          var endDate = new Date(document.getElementById('project_end').value);

          if (endDate && endDate < startDate) {
            alert('End date cannot be less than start date!');
            return;
          }

          // Proceed with form submission
          this.submit();
        });
    </script>
{% endblock %}

ProjectManager/PMApp/templates/view_members.html
{% extends 'base.html' %}

{% block navbar %}
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'dashboard' %}">Dashboard</a></li>
      <li class="navbar-item"><a class="me-2" style="color: F8F9FA; text-decoration: none;" href="{% url 'view_members' %}">Members</a></li>
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'view_project' %}">Overview</a></li>
      <li><a class="mr-2" style="color: ADB5BD; text-decoration: none;" href="{% url "logout" %}">Logout</a></li>
{% endblock %}

{% block content %}

    <!-- TODO DELETE MEMBERS -->
    <div class ="row">
      <div class="mt-4" style="position: relative; left: 76%">
        {% if user.staff_type != "Em" and project.project_status != 2 %}
          <a href="{% url "add_member"%}">
              <button class="btn btn-outline-success" type="button" style="width: 150px;">Add Members</button>
          </a>
        {% endif %}
      </div>
    </div>

    <!-- TODO: View members -->
    <table class="table table-striped rounded-3 overflow-hidden" style="width: 50%; margin:auto; margin-top: 3%">
      <thead class="table table-secondary table-striped">
        <tr>
          <th scope="col" style="width: 50%">Name</th>
          <th scope="col" style="width: 50%">Role</th>
          {% if user.staff_type != "Em" and project.project_status != 2 %}
          <th scope="col" style="width: 10%"></th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
    {% for member in members %}
        <tr>
          <td scope="col"> {{ member.user.name }} </td>
          <td scope="col"> {{ member.user.get_staff_type_display }}</td>

          {% if user.staff_type != "Em" and project.project_status != 2  %}
          <td scope="col"> 
            <a href="{% url "remove_member" member_id=member.member_id %}" method="POST">
              <button class="btn btn-outline-danger" type="button" style="width: 100px">Remove</button>
            </a>
          </td>
          {% endif %}

        </tr>
    {% endfor %}
      </tbody>
    </table>

 
{% endblock %}

ProjectManager/PMApp/templates/view_project.html
{% extends 'base.html' %}
{% load static %}


{% block navbar %}
 
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'dashboard' %}">Dashboard</a></li>
      <li class="navbar-item"><a class="me-2" style="color: ADB5BD; text-decoration: none;" href="{% url 'view_members' %}">Members</a></li>
      <li class="navbar-item"><a class="me-2" style="color: F8F9FA; text-decoration: none;" href="{% url 'view_project' %}">Overview</a></li>
      <li><a class="mr-2" style="color: ADB5BD; text-decoration: none;" href="{% url "logout" %}">Logout</a></li>

{% endblock %}

{% block content %}
<div style="color: WHITE;">
  <div class="row mt-3" style="margin-left: 10px;">
    <div class="col-8">
      <h1>Project Name: {{ project.project_name }} </h1>
    </div>
    <div class="col mb-1">

      {% if user.staff_type == "M" %}
        <!-- Do not show edit details if project is "Archived" -->
        {% if project.project_status != 2 %}
        <a href="{% url 'update_project' %}">
            <button class="btn btn-outline-success" type="button" style="width: 150px;">Edit Details</button>
        </a>
        {% endif %}
        
        <!-- Show archive project button only if project status is "Finished" -->
        {% if project.project_status == 1 %}
        <a href="{% url 'archive_project' %}">
            <button class="btn btn-outline-warning" type="button" style="width: 150px;">Archive Project</button>
        </a>      
        {% endif %}

        <!-- Show unarchive and delete button only if project status is "Archived" -->
        {% if project.project_status == 2 %}
        <a href="{% url 'archive_project' %}">
            <button class="btn btn-outline-warning" type="button" style="width: 150px;">Unarchive Project</button>
        </a>   
        <a href="{% url 'delete_project' %}" >
            <button class="btn btn-outline-danger" type="button" style="width:150px;">Delete Project</button>
        </a>
        {% endif %}
      {% endif %}
    </div> 
  </div> 

  <div class="mb-3" style="height: 1px; background-color: #EAEFF5"></div>
  <!-- line break -->
  <div class="row" style="margin-left: 5px;">
    <div class="col">
      <h2 style="font-size: 26px;"> Description </h2>
    </div>
  </div>

  <div class="row" style="margin-left: 5px; width: 95%">
    <p style="text-justify: auto;"> {{ project.project_desc }} </p>
  </div>

  <div class="mb-3" style="height: 1px; background-color: #EAEFF5"></div>
  <!-- line break -->

  <div class="row">
    <div class="col">
      <div class="row" style="margin-left: 5px;">
        <div class="col-5">
          <h2>Project Start:</h2>
        </div>
        <div class="col">
          <h3> {{ project.project_start }} </h3>
        </div>
      </div>

      <div class="row" style="margin-left: 5px;">
        <div class="col-5">
          <h2>Project End:</h2>
        </div>
        
        <div class="col">
          <h3> {{ project.project_end }} </h3> 
        </div>
      </div>
    </div>

    <div class="col-5">
      <h2 class="ms-3"> Days until End of Project </h2>
      <div class="progress mb-3" role="progressbar" style="height: 20px; width: 70%;">
        <div class="progress-bar bg-success" style="width: {{start_to_now_percentage}}%; color: BLACK"> {{ start_to_now }} days done </div>
        <div class="progress-bar bg-light" style="width: {{end_to_now_percentage}}%; color: BLACK"> {{ end_to_now }} days left </div>
      </div>
    </div>
  </div>
  <div class="mb-3" style="height: 1px; background-color: #EAEFF5"></div>
  <!-- line break -->
  
  <div class="row">
    <div class="col-3">
      <h2 style="margin-left: 18px;">Project Status:</h2>
    </div>
    <div class="col">
      <h2> {{ project.get_project_status_display }} </h2> 
    </div>
      <!-- For IntegerChoices / TextChoices, use {{ OBJNAME.get_FIELDNAME_display }} -->
  </div>

  <!-- Scripting Stuff ig --> 
  <div class="mb-3" style="height: 1px; background-color: #EAEFF5"></div>
  <!-- line break -->
  <div class="col">
    <h2 class="ms-3"> Overall Task Progress </h2>
  </div>

  <div class="progress mb-3" role="progressbar"  style="height: 20px; width: 75%; margin-left: 12%">
    <div class="progress-bar bg-danger" style="width: {{progress}}%"> In Progress</div>
    <div class="progress-bar bg-warning" style="width: {{review}}%"> For Review</div>
    <div class="progress-bar bg-success" style="width: {{completed}}%"> Completed </div>
  </div>

  <div class="mb-3" style="height: 1px; background-color: #EAEFF5"></div>
  <!-- line break -->

  {% if user.staff_type == "M" or user.staff_type == "X" %}
  <h2 class="ms-3"> Financial Summary </h2>
  
  <!-- TABLE OF EXPENSES PLUS THE TOTAL EXPENSES -->
  <div class="ms-3">
    <div class="col">
      {% load humanize %}
      <h2> Total Expenses: {{ total_expenses|floatformat:2|intcomma }} PHP</h2>
    </div>
  </div>
  {% endif %}

</div>

{% endblock %}